name: Publish docker image
on:
  release:
    types: [published]
jobs:
  push_to_repo:
    name: Push Docker images to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Push to docker hub
        uses: docker/build-publish-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kvitrvn/php
          tag_with_ref: true